version: '3.8'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./logs:/logs
    working_dir: /app
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    command: ./wait-for-mysql.sh

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    volumes:
      - ./logs/nginx:/var/log/nginx



volumes:
  db_data:
