global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'frontend'
    static_configs:
      - targets: ['nginx:80']
        labels:
          job: 'angular_frontend'


  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8089']

  - job_name: 'frontend-container'
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'prometheus'
    static_configs:
        - targets: [ 'localhost:9090' ]
